### ISSUE TITLE
Свойства у body

### ISSUE THREAD

**Issue by liga-teamlead** [Azune-NK/es6-gulp-template#10]
Слишком много свойств у body разбросано по нескольким файлам, это неудобно. Лучше создать какой-либо файлик general или взять какой-то из существующих и запихнуть туда все свойства. Чтобы всё было в 1м месте.

**Comment by Azune-NK** [comment]
Да, спасибо. Файл с типографией из прошлого тянется. В следующем обновлении объединю.
