### ISSUE TITLE
Кроссбраузерное прибитие футера

### ISSUE THREAD

**Issue by Azune-NK** [Azune-NK/es6-gulp-template#3]
Текущее решение с flex не работает в ie11.

**Comment by ViktorProdeus** [comment]
Рабочее решение  <a href="https://codepen.io/webinmind/pen/WWxGeO/">прижатие футера к низу страницы</a> , вроде как работает в Ie11

**Comment by liga-teamlead** [comment]
Сделала ПР для IE.

**Comment by Azune-NK** [comment]
Спасибо, проблема решена. #8
