### ISSUE TITLE
Обнаружено 2 ошибки

### ISSUE THREAD

**Issue by NikolayLemehov** [Azune-NK/es6-gulp-template#6]
Пишу сюда по рекомендации Даши Владыко.

Обнаружено 2 ошибки:
- editorconfig не проверяет html, который вложенный в папки. Если в package.json [добавить](https://prnt.sc/tdidgm) как в js, svg и sass, то тогда проверяет.
- npm test работает не полностью. Если ошибка возникает при проверке editorconfig, то не проверяют stylelint и eslint. Если ошибок editorconfig не обнаружил, а обнаружил stylelint, то на этом проверка останавливается и eslint не проверяет. Если в package.json [заменить](https://prnt.sc/tdiiqh) "&&" на "&", то тогда проверяет всё сразу.

**Comment by NikolayLemehov** [comment]
Создан [Pull request](https://github.com/Azune-NK/es6-gulp-template/pull/7), который решает эту задачу.

**Comment by Azune-NK** [comment]
Спасибо. #7
